-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) as SALES
FROM OFFLINE_SALE as o
LEFT JOIN PRODUCT as p ON o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC
